### ISSUE TITLE
Cannot access Document.name if not saved.

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#12]
Hi @TomRuark @isonno,
is there any chance to get the doc name even if has never been saved (a new one)?

Document name should be available instantly, I choose it in the new document dialog :lollipop:

```
Line: 749
->  }).call(this);JSON.stringify(app.activeDocument.path + '/' + app.activeDocument.name)
ThrowHostException caught with host adaptor error: 8103
Exception (ScCore::Error) caught in TProxyBase::BaseGet: 8103
Error 8103: The document has not yet been saved.
```

**Comment by kilianc** [comment]
I think the problem is `app.activeDocument.path` not `app.activeDocument.name`

**Comment by TomRuark** [comment]
Yes. Stick a try/catch around that call and ??? do the right thing accordingly ???
try { a = activeDocument.path; } catch(e) { e.toString(); }

**Comment by TomRuark** [comment]
HA! I now see that this is "closed the issue 2 months ago" guess I'm a bit late!

**Comment by kilianc** [comment]
Yep ;)

BTW doesn't matter now, we don't need to access fs anymore.  

## 

Kilian C.
