### ISSUE TITLE
Send assets over the socket as base64 data url

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#14]
The user is allowed to change document and connect to different PS servers. That means that in order to save assets to the disk we must ask for a working directory for each psd file and the actual state of the project is not ready for that.

Sending assets over the socket is less performant if a local-storage/indexDB caching system is not implemented (not scheduled yet) but will allow motherlover to receive assets without dealing with the fs.

The point is: we do not need persistence right now.

**Comment by kilianc** [comment]
In order to do it once, I need the new streaming API

**Comment by timriot** [comment]
New streaming API in place... unblocking.

**Comment by kilianc** [comment]
not needed anymore, we have a working folder.
