### ISSUE TITLE
Name this thing

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#20]

**Comment by timriot** [comment]
LivePSD
LiveHTML5
CSSPreview
HTML5Preview

**Comment by timriot** [comment]
CSSmuggler
DubCSS
CSStep
PSDMarkup
PSDStyles

**Comment by timriot** [comment]
CSSGenerator
Generator

**Comment by kilianc** [comment]
LiveMarkup
CSS (playing with CS*)

**Comment by timriot** [comment]
Markup...LIVE!

**Comment by timriot** [comment]
GenerateCSS
AutomatiCSS
Switcharoo
The Second Best Idea that we've ever had
MyWaffle
