### ISSUE TITLE
App Wrapper: links

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#23]
## Button Name - URL

Tonight - http://www.youtube.com/watch?v=Sv6dMFF_yts
Chuck - http://www.youtube.com/watch?v=sZz2yCe3pIg
Have you? - http://www.youtube.com/watch?v=J-Q4AkJ9iIU  
The word - http://www.youtube.com/watch?v=2WNrx2jq184
Hey Girl - http://siliconvalleyryangosling.tumblr.com/
Whatever - http://assets0.ordienetworks.com/images/GifGuide/DealWithIt/bieberdealwithit.gif
Dayum - http://www.youtube.com/watch?v=DcJFdCmN98s  
Call me Maybe - http://www.youtube.com/watch?v=dBM7i84BThE
Totally Cancelled - http://www.hulu.com/watch/34464
All the things - http://www.gamesprays.com/files/resource_media/preview/build-all-the-things-5638_preview.jpg

**Comment by kilianc** [comment]
done.

**Comment by kilianc** [comment]
https://github.com/kilianc/motherlover/blob/macapp/Motherlover/Classes/MLAppDelegate.m#L21

done.
