### ISSUE TITLE
Text transformations don't affect text size value

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#31]
For instance, I created a text layer and the value was on 2.2pt, then I used cmd+t to scale it proportionally.
The photoshop UI is showing me the right value, the layer descriptor not.

```
textKey.transform.xx: 251.474362624563
textKey.transform.xy: 0
textKey.transform.yx: 0
textKey.transform.yy: 249.211367335191
textKey.transform.tx: 0
textKey.transform.ty: 0
textKey.textStyleRange[0].from: 0
textKey.textStyleRange[0].to: 4
textKey.textStyleRange[0].textStyle.size: 2.2pt
```

@isonno, @TomRuark should I apply the matrix manually?

**Comment by timriot** [comment]
From what I've heard, this is how it actually works under the hood, IE they maintain the original point size value, then multiple that value times the transform and display the appropriate pt size in the UI. WHY, is anyone's guess.

**Comment by kilianc** [comment]
Well, closing as **wontfix**

The way PS works is multiplying the yy value for the size value. I think using a delta xx-yy as transform css property I can make the text look the same as PS.
