### ISSUE TITLE
User research request: Round tripping, IE reading HTML5 into PSD

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#46]

**Comment by kilianc** [comment]
You mean, html to psd?

## 

Kilian C.

**Comment by timriot** [comment]
html + css into PSD, yeah. crazy as it may sound.

**Comment by kilianc** [comment]
you can do it, I can not see why you should :)

## 

Kilian C.

**Comment by kilianc** [comment]
How should we consider this? imho closed.
