### ISSUE TITLE
Checkout the Reflow source code on github (via triot) and discern what it would take to get ML and Reflow talking

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#51]
Since we're blocked on a lot of other fronts, this seems like a decent use of your time. What do you think, Kilian?

**Comment by kilianc** [comment]
Seems like a good idea actually.
Any update on that front?

## 

Kilian C.

**Comment by timriot** [comment]
I haven't heard back. I'll pull the source if I can figure out how to do that through the stupid Adobe enterprise version of github.

**Comment by kilianc** [comment]
`git clone [url]`

P.S. isn't that exactly the same as github?  

## 

Kilian C.

**Comment by timriot** [comment]
the process is the same, sure, but the crazy authentication method they use seems to make using things like tower or the CLI very difficult.

**Comment by timriot** [comment]
I've sent Kilian the source for reflow... closing.
