### ISSUE TITLE
ETA for new PS API.

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#52]
Still waiting for some sort of estimate time.

**Comment by timriot** [comment]
I'm working on this right now. I've got a meeting with Tim Wright to talk about this tomorrow.

**Comment by timriot** [comment]
Current ETA for an initial stab is next Friday.

**Comment by kilianc** [comment]
:facepunch: :clap:

**Comment by kilianc** [comment]
Still true that we will get the build on Tue/16th?

**Comment by timriot** [comment]
From what I understand, we should get a proper build by 10/16.

**Comment by timriot** [comment]
should be in now. I've uploaded the latest build to Kilian.
