### ISSUE TITLE
Think of ways to integrate CSS FilterLab with Generator

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#56]
http://html.adobe.com/webstandards/csscustomfilters/cssfilterlab/

Got any ideas? I'm meeting with these folks on Friday to demo and start the conversation.

**Comment by kilianc** [comment]
Not really, it seem a css filter preview to me, maybe a widget for inline editing?

**Comment by timriot** [comment]
I have spoken with these folks. They are very interested in developing output plugins for ML when that architecture is ready. Until then, there is nothing more to be done. Closing.
