### ISSUE TITLE
renaming a layer with a tag causes a crash (ex. renaming "bill.jpg" to "ted.jpg")

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#66]
11/29/2012 03:32:20: {"message":"assetsPath is not defined","stack":"ReferenceError: assetsPath is not defined\n    at removeAsset (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:169:21)\n    at Photoshop.ps.connect.ps.on.layer (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:45:9)\n    at Photoshop.EventEmitter.emit (events.js:126:20)\n    at dispatchMessage (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:291:10)\n    at Photoshop.fillPayload (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:271:7)\n    at Photoshop.readMessageLength (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:244:8)\n    at Socket.g (events.js:192:14)\n    at Socket.EventEmitter.emit (events.js:96:17)\n    at TCP.onread (net.js:396:14)","code":"UNCAUGHT_EXCEPTION"}

**Comment by kilianc** [comment]
I think you are using an old build, I fixed this yesterday.
Please confirm and close

**Comment by timriot** [comment]
Drop me the latest again?

**Comment by kilianc** [comment]
already there, isn't it?

## 

Kilian C.

**Comment by kilianc** [comment]
closing for now, reopen if necessary.
