### ISSUE TITLE
 Tagged groups with no contents cause crashes, with no output.

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#68]
The server just stops or nothing happens.

**Comment by kilianc** [comment]
can you drop me the latest cocoa client?
Photoshop goes to 100% cpu, I want to test it with another client.

**Comment by timriot** [comment]
I will pull this for you later tonight...

**Comment by kilianc** [comment]
100% positive it's PS.
I am now skipping empty groups.
