### ISSUE TITLE
Dedicated, independent server outside of Remote Connections for ML

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#7]
Problems:
 Connection setup is a pain and requires several additional steps
 API to setup a password?

Questions:
 If this is for local machines only, why can't we have a separate, unencrypted server that is tied to localhost only and will not allow remote connections.

**Comment by timriot** [comment]
I will begin looking into this much more deeply.

**Comment by kilianc** [comment]
We don't even need tcp. We just need some kind of bridgetalk + kevlar.

## 

Kilian C.

**Comment by timriot** [comment]
Word. There _must_ be a way.

-Tim
