### ISSUE TITLE
Deleting tagged layers / groups does not delete the corresponding image

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#77]

**Comment by kilianc** [comment]
It does work on both my macbook and non dev iMac, can you attach the psd and the log?

**Comment by timriot** [comment]
I will re-test and put the problematic PSD here, if I am still able to
reproduce.

-Tim

**Comment by timriot** [comment]
Ok, so deleting layers sort of works in this file, unfortunately, right after deleting, ML crashes:

12/01/2012 12:24:17: {"message":"Cannot call method 'split' of undefined","stack":"TypeError: Cannot call method 'split' of undefined\n    at Photoshop.parseLayer (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:99:30)\n    at Photoshop.EventEmitter.emit (events.js:126:20)\n    at dispatchMessage (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:291:10)\n    at Photoshop.fillPayload (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:271:7)\n    at Photoshop.readMessageLength (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:244:8)\n    at Socket.g (events.js:192:14)\n    at Socket.EventEmitter.emit (events.js:96:17)\n    at TCP.onread (net.js:396:14)","code":"UNCAUGHT_EXCEPTION"}

Deleting groups doesn't work at all.

**Comment by timriot** [comment]
Here's a link to the PSD in question:

https://www.dropbox.com/s/ek8tdbpdbhoo7mb/shapes.psd
