### ISSUE TITLE
Bitmap streaming API

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#8]
This API should allow a client connected to the PS JS Server, to get a group/layer flattened rapresentation in the provided format, following the provided format options.

The request will carry an options dictionary like the following one

``` js
{
    document_id: Number,
    layer_id: Number,   
    format: {
        name: String,
        compression: /* example */,
        transparency: /* example */
    }
}
```

The first version of this API will support only the `"bitmap"` format name. No additional options are needed.

This API should be non blocking, in order to allow the user to keep working without noticing weird behaviors of the UI.

**Comment by timriot** [comment]
Question from Tom R - Are we expecting a bitmap object which represents a composite of several layers (group) to also include positioning information or are we going to want to figure that out ourselves. I am assuming we will want to receive the pixels, as well as the positioning info. Let me know and I'll forward along.

**Comment by kilianc** [comment]
We don't need position data, we just need the bounds cropped bitmap. It's a separate call on a different layer than the DOM one.  

## 

Kilian C.
