### ISSUE TITLE
Crash: When trying to add a new group

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#80]
11/30/2012 11:38:10: {"message":"Cannot call method 'split' of undefined","stack":"TypeError: Cannot call method 'split' of undefined\n    at Photoshop.parseLayer (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:99:30)\n    at Photoshop.EventEmitter.emit (events.js:99:17)\n    at dispatchMessage (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:291:10)\n    at Photoshop.fillPayload (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:271:7)\n    at Photoshop.readMessageLength (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:244:8)\n    at Socket.g (events.js:192:14)\n    at Socket.EventEmitter.emit (events.js:96:17)\n    at TCP.onread (net.js:396:14)","code":"UNCAUGHT_EXCEPTION"}

**Comment by kilianc** [comment]
fixed in d9b3b7407cd6ed453fac3e1df665a5190414b2e8
