### ISSUE TITLE
Crash: When grouping a series of layers together (by selecting layers and command + G)

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#81]
11/30/2012 11:43:33: {"message":"Cannot read property 'name' of undefined","stack":"TypeError: Cannot read property 'name' of undefined\n    at Photoshop.ps.connect.ps.on.layer (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:41:24)\n    at Photoshop.EventEmitter.emit (events.js:126:20)\n    at dispatchMessage (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:291:10)\n    at Photoshop.fillPayload (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:271:7)\n    at Photoshop.readMessageLength (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:244:8)\n    at Socket.g (events.js:192:14)\n    at Socket.EventEmitter.emit (events.js:96:17)\n    at TCP.onread (net.js:396:14)","code":"UNCAUGHT_EXCEPTION"}

**Comment by kilianc** [comment]
Actually, cmd-g-ing layers doesn't trigger any event, I think that was related to another bug (fixed).
I'll keep this open as blocked.

**Comment by kilianc** [comment]
fixed.
