### ISSUE TITLE
Auto-updating engine - Sparkle (Mac) / ??? (Win)

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#82]
It would be excellent if we could build an auto-updating feature into ML (via Sparkle?), so that our work could continue past the GM date of PS.

**Comment by kilianc** [comment]
it's already there, I just need to push the update and test if it really works :)

## 

Kilian C.

**Comment by timriot** [comment]
yoooooou are the chaaampion
my friend!
aaaand yoooooou'll keep on fiiiighting
'til the end!
you are the champion
you aaaaare the champion
no time for losers
'cause yoooooou are the champion
(dunh dunh)
...of the woooorld!

**Comment by timriot** [comment]
Closing as we are taking a different approach.
