### ISSUE TITLE
Is the 127 message limit for Kevlar requiring a restart or otherwise causing any extra work for ML?

### ISSUE THREAD

**Issue by timriot** [kilianc/adobe-generator#86]
Should we get the message limit increased for any reason?

**Comment by kilianc** [comment]
? nope.

The limit is on the messageId, N {0-127).
PS js server is request/response so there's no concept of parallel message processing per client,
at least in the way I implemented it.

## 

Kilian C.

**Comment by timriot** [comment]
Sounds reasonable. Just wanted to check. Thanks for the answer!
